# Generated by Django 3.0.8 on 2020-09-09 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('welcome', '0002_auto_20200909_1153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='content',
            field=models.CharField(max_length=5000),
        ),
    ]
