# Generated by Django 3.0.8 on 2020-09-11 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('welcome', '0005_coworker'),
    ]

    operations = [
        migrations.AddField(
            model_name='actor',
            name='short',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='comment',
            name='short',
            field=models.TextField(default=''),
        ),
    ]
