# Generated by Django 3.0.8 on 2020-09-11 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('welcome', '0006_auto_20200911_0927'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='actor',
            name='short',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='short',
        ),
    ]
