# Generated by Django 3.0.5 on 2020-09-11 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('welcome', '0007_auto_20200911_0942'),
    ]

    operations = [
        migrations.AddField(
            model_name='actor',
            name='short',
            field=models.TextField(default='/'),
        ),
    ]
